-- Países participantes: todos ativos por padrão; o admin pode
-- desativar países onde o app não deva operar (censura/legal).
CREATE TABLE IF NOT EXISTS countries (
  code    TEXT PRIMARY KEY,
  name_pt TEXT NOT NULL,
  name_en TEXT NOT NULL,
  active  BOOLEAN NOT NULL DEFAULT TRUE
);

INSERT INTO countries (code, name_pt, name_en) VALUES
  ('AG', 'Antígua e Barbuda', 'Antigua and Barbuda'),
  ('AR', 'Argentina', 'Argentina'),
  ('BS', 'Bahamas', 'Bahamas'),
  ('BB', 'Barbados', 'Barbados'),
  ('BZ', 'Belize', 'Belize'),
  ('BO', 'Bolívia', 'Bolivia'),
  ('BR', 'Brasil', 'Brazil'),
  ('CA', 'Canadá', 'Canada'),
  ('CL', 'Chile', 'Chile'),
  ('CO', 'Colômbia', 'Colombia'),
  ('CR', 'Costa Rica', 'Costa Rica'),
  ('CU', 'Cuba', 'Cuba'),
  ('DM', 'Dominica', 'Dominica'),
  ('DO', 'República Dominicana', 'Dominican Republic'),
  ('EC', 'Equador', 'Ecuador'),
  ('SV', 'El Salvador', 'El Salvador'),
  ('GD', 'Granada', 'Grenada'),
  ('GT', 'Guatemala', 'Guatemala'),
  ('GY', 'Guiana', 'Guyana'),
  ('HT', 'Haiti', 'Haiti'),
  ('HN', 'Honduras', 'Honduras'),
  ('JM', 'Jamaica', 'Jamaica'),
  ('MX', 'México', 'Mexico'),
  ('NI', 'Nicarágua', 'Nicaragua'),
  ('PA', 'Panamá', 'Panama'),
  ('PY', 'Paraguai', 'Paraguay'),
  ('PE', 'Peru', 'Peru'),
  ('KN', 'São Cristóvão e Névis', 'Saint Kitts and Nevis'),
  ('LC', 'Santa Lúcia', 'Saint Lucia'),
  ('VC', 'São Vicente e Granadinas', 'Saint Vincent and the Grenadines'),
  ('SR', 'Suriname', 'Suriname'),
  ('TT', 'Trinidad e Tobago', 'Trinidad and Tobago'),
  ('US', 'Estados Unidos', 'United States'),
  ('UY', 'Uruguai', 'Uruguay'),
  ('VE', 'Venezuela', 'Venezuela'),
  ('AL', 'Albânia', 'Albania'),
  ('AD', 'Andorra', 'Andorra'),
  ('AT', 'Áustria', 'Austria'),
  ('BY', 'Bielorrússia', 'Belarus'),
  ('BE', 'Bélgica', 'Belgium'),
  ('BA', 'Bósnia e Herzegovina', 'Bosnia and Herzegovina'),
  ('BG', 'Bulgária', 'Bulgaria'),
  ('HR', 'Croácia', 'Croatia'),
  ('CY', 'Chipre', 'Cyprus'),
  ('CZ', 'Tchéquia', 'Czechia'),
  ('DK', 'Dinamarca', 'Denmark'),
  ('EE', 'Estônia', 'Estonia'),
  ('FI', 'Finlândia', 'Finland'),
  ('FR', 'França', 'France'),
  ('DE', 'Alemanha', 'Germany'),
  ('GR', 'Grécia', 'Greece'),
  ('HU', 'Hungria', 'Hungary'),
  ('IS', 'Islândia', 'Iceland'),
  ('IE', 'Irlanda', 'Ireland'),
  ('IT', 'Itália', 'Italy'),
  ('LV', 'Letônia', 'Latvia'),
  ('LI', 'Liechtenstein', 'Liechtenstein'),
  ('LT', 'Lituânia', 'Lithuania'),
  ('LU', 'Luxemburgo', 'Luxembourg'),
  ('MT', 'Malta', 'Malta'),
  ('MD', 'Moldávia', 'Moldova'),
  ('MC', 'Mônaco', 'Monaco'),
  ('ME', 'Montenegro', 'Montenegro'),
  ('NL', 'Holanda', 'Netherlands'),
  ('MK', 'Macedônia do Norte', 'North Macedonia'),
  ('NO', 'Noruega', 'Norway'),
  ('PL', 'Polônia', 'Poland'),
  ('PT', 'Portugal', 'Portugal'),
  ('RO', 'Romênia', 'Romania'),
  ('RU', 'Rússia', 'Russia'),
  ('SM', 'San Marino', 'San Marino'),
  ('RS', 'Sérvia', 'Serbia'),
  ('SK', 'Eslováquia', 'Slovakia'),
  ('SI', 'Eslovênia', 'Slovenia'),
  ('ES', 'Espanha', 'Spain'),
  ('SE', 'Suécia', 'Sweden'),
  ('CH', 'Suíça', 'Switzerland'),
  ('UA', 'Ucrânia', 'Ukraine'),
  ('GB', 'Reino Unido', 'United Kingdom'),
  ('VA', 'Vaticano', 'Vatican City'),
  ('DZ', 'Argélia', 'Algeria'),
  ('AO', 'Angola', 'Angola'),
  ('BJ', 'Benim', 'Benin'),
  ('BW', 'Botsuana', 'Botswana'),
  ('BF', 'Burquina Fasso', 'Burkina Faso'),
  ('BI', 'Burundi', 'Burundi'),
  ('CV', 'Cabo Verde', 'Cabo Verde'),
  ('CM', 'Camarões', 'Cameroon'),
  ('CF', 'República Centro-Africana', 'Central African Republic'),
  ('TD', 'Chade', 'Chad'),
  ('KM', 'Comores', 'Comoros'),
  ('CG', 'Congo', 'Congo'),
  ('CD', 'RD Congo', 'DR Congo'),
  ('CI', 'Costa do Marfim', 'Côte d''Ivoire'),
  ('DJ', 'Djibuti', 'Djibouti'),
  ('EG', 'Egito', 'Egypt'),
  ('GQ', 'Guiné Equatorial', 'Equatorial Guinea'),
  ('ER', 'Eritreia', 'Eritrea'),
  ('SZ', 'Essuatíni', 'Eswatini'),
  ('ET', 'Etiópia', 'Ethiopia'),
  ('GA', 'Gabão', 'Gabon'),
  ('GM', 'Gâmbia', 'Gambia'),
  ('GH', 'Gana', 'Ghana'),
  ('GN', 'Guiné', 'Guinea'),
  ('GW', 'Guiné-Bissau', 'Guinea-Bissau'),
  ('KE', 'Quênia', 'Kenya'),
  ('LS', 'Lesoto', 'Lesotho'),
  ('LR', 'Libéria', 'Liberia'),
  ('LY', 'Líbia', 'Libya'),
  ('MG', 'Madagáscar', 'Madagascar'),
  ('MW', 'Malaui', 'Malawi'),
  ('ML', 'Mali', 'Mali'),
  ('MR', 'Mauritânia', 'Mauritania'),
  ('MU', 'Maurício', 'Mauritius'),
  ('MA', 'Marrocos', 'Morocco'),
  ('MZ', 'Moçambique', 'Mozambique'),
  ('NA', 'Namíbia', 'Namibia'),
  ('NE', 'Níger', 'Niger'),
  ('NG', 'Nigéria', 'Nigeria'),
  ('RW', 'Ruanda', 'Rwanda'),
  ('ST', 'São Tomé e Príncipe', 'São Tomé and Príncipe'),
  ('SN', 'Senegal', 'Senegal'),
  ('SC', 'Seicheles', 'Seychelles'),
  ('SL', 'Serra Leoa', 'Sierra Leone'),
  ('SO', 'Somália', 'Somalia'),
  ('ZA', 'África do Sul', 'South Africa'),
  ('SS', 'Sudão do Sul', 'South Sudan'),
  ('SD', 'Sudão', 'Sudan'),
  ('TZ', 'Tanzânia', 'Tanzania'),
  ('TG', 'Togo', 'Togo'),
  ('TN', 'Tunísia', 'Tunisia'),
  ('UG', 'Uganda', 'Uganda'),
  ('ZM', 'Zâmbia', 'Zambia'),
  ('ZW', 'Zimbábue', 'Zimbabwe'),
  ('AF', 'Afeganistão', 'Afghanistan'),
  ('AM', 'Armênia', 'Armenia'),
  ('AZ', 'Azerbaijão', 'Azerbaijan'),
  ('BH', 'Barém', 'Bahrain'),
  ('BD', 'Bangladesh', 'Bangladesh'),
  ('BT', 'Butão', 'Bhutan'),
  ('BN', 'Brunei', 'Brunei'),
  ('KH', 'Camboja', 'Cambodia'),
  ('CN', 'China', 'China'),
  ('GE', 'Geórgia', 'Georgia'),
  ('IN', 'Índia', 'India'),
  ('ID', 'Indonésia', 'Indonesia'),
  ('IR', 'Irã', 'Iran'),
  ('IQ', 'Iraque', 'Iraq'),
  ('IL', 'Israel', 'Israel'),
  ('JP', 'Japão', 'Japan'),
  ('JO', 'Jordânia', 'Jordan'),
  ('KZ', 'Cazaquistão', 'Kazakhstan'),
  ('KW', 'Kuwait', 'Kuwait'),
  ('KG', 'Quirguistão', 'Kyrgyzstan'),
  ('LA', 'Laos', 'Laos'),
  ('LB', 'Líbano', 'Lebanon'),
  ('MY', 'Malásia', 'Malaysia'),
  ('MV', 'Maldivas', 'Maldives'),
  ('MN', 'Mongólia', 'Mongolia'),
  ('MM', 'Mianmar', 'Myanmar'),
  ('NP', 'Nepal', 'Nepal'),
  ('KP', 'Coreia do Norte', 'North Korea'),
  ('OM', 'Omã', 'Oman'),
  ('PK', 'Paquistão', 'Pakistan'),
  ('PS', 'Palestina', 'Palestine'),
  ('PH', 'Filipinas', 'Philippines'),
  ('QA', 'Catar', 'Qatar'),
  ('SA', 'Arábia Saudita', 'Saudi Arabia'),
  ('SG', 'Singapura', 'Singapore'),
  ('KR', 'Coreia do Sul', 'South Korea'),
  ('LK', 'Sri Lanka', 'Sri Lanka'),
  ('SY', 'Síria', 'Syria'),
  ('TJ', 'Tadjiquistão', 'Tajikistan'),
  ('TH', 'Tailândia', 'Thailand'),
  ('TL', 'Timor-Leste', 'Timor-Leste'),
  ('TR', 'Turquia', 'Turkey'),
  ('TM', 'Turcomenistão', 'Turkmenistan'),
  ('AE', 'Emirados Árabes Unidos', 'United Arab Emirates'),
  ('UZ', 'Uzbequistão', 'Uzbekistan'),
  ('VN', 'Vietnã', 'Vietnam'),
  ('YE', 'Iêmen', 'Yemen'),
  ('AU', 'Austrália', 'Australia'),
  ('FJ', 'Fiji', 'Fiji'),
  ('KI', 'Quiribati', 'Kiribati'),
  ('MH', 'Ilhas Marshall', 'Marshall Islands'),
  ('FM', 'Micronésia', 'Micronesia'),
  ('NR', 'Nauru', 'Nauru'),
  ('NZ', 'Nova Zelândia', 'New Zealand'),
  ('PW', 'Palau', 'Palau'),
  ('PG', 'Papua-Nova Guiné', 'Papua New Guinea'),
  ('WS', 'Samoa', 'Samoa'),
  ('SB', 'Ilhas Salomão', 'Solomon Islands'),
  ('TO', 'Tonga', 'Tonga'),
  ('TV', 'Tuvalu', 'Tuvalu'),
  ('VU', 'Vanuatu', 'Vanuatu')
ON CONFLICT (code) DO NOTHING;
